name: deeponet-learnext

channels:
  - pytorch
  - nvidia
  - conda-forge

dependencies:
  - python=3.10
  - pytorch
  - pytorch-cuda=12.1
  - fenics
  - gmsh
  - python-gmsh
  - meshio
  - pyvista
  - numpy
  - matplotlib
  - ipykernel
  - tqdm
  - pytest
  - pyyaml

variables:
  DL_TEST_VAR: testValue
  DL_PASS_OVERWRITE: 0
